# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

services:
  - mssql2014

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - c:\Windows\SysWOW64\odbcconf.exe /a {CONFIGSYSDSN "SQL Server" "DSN=test|Description=test|Trusted_Connection=no|SERVER=(local)\SQL2014"}
test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
  - provider: Slack
    auth_token:
      secure: g/jk3Nm7fwY8+d3pnGR9S6TWXFBqVlaMRIfXsCPCTwGKZCwLxHBq7YnEMMyaO14Ttb/KtdjVQAHYSFgnVPNMnA==
    channel: ci
    template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_"
